### ISSUE TITLE
Conf file placed locally in /etc/drauger-locales/ is not interpreted correctly

### ISSUE THREAD

**Issue by ono-taka179** [drauger-os-development/drauger-welcome#25]
The following is the error output from running drauger-welcome with the conf file in /etc/drauger-locales/.

```
Traceback (most recent call last):
  File "/usr/bin/drauger-welcome", line 76, in <module>
    launch(False)
  File "/usr/bin/drauger-welcome", line 62, in launch
    drauger_welcome.main_ui.welcome_show()
  File "/usr/lib/python3/dist-packages/drauger_welcome/main_ui.py", line 1197, in welcome_show
    window = welcome()
             ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/drauger_welcome/main_ui.py", line 238, in __init__
    self.reset("clicked")
  File "/usr/lib/python3/dist-packages/drauger_welcome/main_ui.py", line 257, in reset
    self.label.set_markup(welcome_label)
                          ^^^^^^^^^^^^^
NameError: name 'welcome_label' is not defined
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 228, in partial_apport_excepthook
    return apport_excepthook(binary, exc_type, exc_obj, exc_tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 123, in apport_excepthook
    report.add_package_info()
  File "/usr/lib/python3/dist-packages/apport/report.py", line 442, in add_package_info
    package = apport.fileutils.find_file_package(self["ExecutablePath"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 175, in find_file_package
    return packaging.get_file_package(file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apport/packaging_impl/rpm.py", line 158, in get_file_package
    raise NotImplementedError(
NotImplementedError: method must be implemented by distro-specific RPMPackageInfo subclass

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/drauger-welcome", line 76, in <module>
    launch(False)
  File "/usr/bin/drauger-welcome", line 62, in launch
    drauger_welcome.main_ui.welcome_show()
  File "/usr/lib/python3/dist-packages/drauger_welcome/main_ui.py", line 1197, in welcome_show
    window = welcome()
             ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/drauger_welcome/main_ui.py", line 238, in __init__
    self.reset("clicked")
  File "/usr/lib/python3/dist-packages/drauger_welcome/main_ui.py", line 257, in reset
    self.label.set_markup(welcome_label)
                          ^^^^^^^^^^^^^
NameError: name 'welcome_label' is not defined
```

**Comment by Batcastle** [comment]
Fixed by #26 and #27
